version: "3.1"
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  db:
    restart: always
    image: postgres:12
    environment:
      POSTGRES_DB: $SQL_DATABASE
      POSTGRES_USER: $SQL_USER
      POSTGRES_PASSWORD: $SQL_PASSWORD
    volumes:
      - persistent:/var/lib/postgresql/data/
    networks:
      - default
  pgadmin:
    container_name: pgadmin4_container_django
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  web:
    restart: always
    build:
      context: .
    volumes:
      - .:/app
      - static:/static
    expose:
      - 8000
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
#      sh -c "gunicorn adra_project.wsgi --log-level=debug  --threads=2 --bind  0.0.0.0:8000"

    #      python manage.py migrate --no-input &&
    #python manage.py runserver 0.0.0.0:8000 "
    #gunicorn adra_project.wsgi --bind  0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
    links:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=HostRegexp(`localhost`,`{subhost:[a-zA-Z0-9-]+}.localhost`)"

  traefik:
    image: traefik:v2.9.5
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik/traefik.dev.toml:/etc/traefik/traefik.toml"

  celery:
    restart: always
    build:
      context: .
    command: celery --app=adra_project worker -l info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis

  celery-beat:
    restart: always
    build:
      context: .
    command: celery --app=adra_project beat -l info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis

volumes:
  persistent: { }
  static: { }
