# Generated by Django 3.2.10 on 2022-07-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegaciones', '0002_alter_delegaciones_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegaciones',
            name='calle',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
