# Generated by Django 3.2.10 on 2022-07-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delegaciones', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
