# Generated by Django 3.2.10 on 2022-07-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegaciones', '0005_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiariosGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegacion_name', models.CharField(max_length=350)),
                ('nombre_beneficiario', models.CharField(max_length=250)),
                ('documentacion_beneficiario', models.CharField(max_length=250)),
                ('ciudad', models.CharField(max_length=256)),
                ('provincia', models.CharField(max_length=256)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
