# Generated by Django 3.2.10 on 2022-07-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegaciones', '0006_beneficiariosglobales'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiariosglobales',
            name='delegacion_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
