# Generated by Django 3.2.10 on 2022-10-28 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delegaciones', '0007_beneficiariosglobales_delegacion_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegaciones',
            name='oar',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
