name: Deploy to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
      - uses: actions/checkout@v2
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          run: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

      - name: Build, tag, and push web image to Docker hub
        env:
          ECR_REGISTRY: ${{secrets.DOCKER_USER}}
          ECR_REPOSITORY: adra-tenant
          IMAGE_TAG_WEB: web
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_WEB .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_WEB

      - name: Build, tag, and push nginx image to Docker hub
        env:
          ECR_REGISTRY: ${{secrets.DOCKER_USER}}
          ECR_REPOSITORY: adra-tenant
          IMAGE_TAG_NGINX: nginx
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_NGINX ./nginx
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_NGINX
