# Generated by Django 3.2.10 on 2022-11-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0002_auto_20221104_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hijo',
            name='parentesco',
            field=models.CharField(max_length=50),
        ),
    ]
