# Generated by Django 3.2.10 on 2022-11-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0003_alter_hijo_parentesco'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sexo',
            field=models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre')], default='mujer', max_length=20),
        ),
    ]
