# Generated by Django 3.2.10 on 2022-12-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0004_profile_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='otros_documentos',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(unique=True),
        ),
    ]
