# Generated by Django 3.2.10 on 2022-12-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0005_auto_20221201_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='persona',
            name='otros_documentos',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
