# Generated by Django 3.2.10 on 2022-12-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0007_remove_persona_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='categoria',
            field=models.CharField(choices=[('1', 'Domingo 2'), ('2', 'Domingo 4')], default='1', max_length=30),
        ),
    ]
