# Generated by Django 3.2.10 on 2022-12-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0008_persona_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='categoria',
        ),
    ]
