# Generated by Django 3.2.10 on 2023-11-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adra', '0011_auto_20230510_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentos',
            name='alimento_13',
            field=models.IntegerField(default=None, verbose_name='Tarritos infantiles fruta'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_14',
            field=models.IntegerField(default=None, verbose_name='Alubias cocidas'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_15',
            field=models.IntegerField(default=None, verbose_name='Conserva de sardina'),
        ),
        migrations.AddField(
            model_name='alimentos',
            name='alimento_16',
            field=models.IntegerField(default=None, verbose_name='Fruta en conserva'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_13',
            field=models.IntegerField(default=0, verbose_name='Tarritos infantiles fruta'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_13_0_3',
            field=models.IntegerField(default=0, verbose_name='Rango 0-3 familia'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_13_4_6',
            field=models.IntegerField(default=0, verbose_name='Rango 4-6 familia'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_13_7_9',
            field=models.IntegerField(default=0, verbose_name='Rango 7-9 familia'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_13_type',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('familia', 'Familia')], default='unidad', max_length=20, verbose_name='Entrega'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_14',
            field=models.IntegerField(default=0, verbose_name='Alubias cocidas'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_14_0_3',
            field=models.IntegerField(default=0, verbose_name='Rango 0-3 familia'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_14_4_6',
            field=models.IntegerField(default=0, verbose_name='Rango 4-6 familia'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_14_7_9',
            field=models.IntegerField(default=0, verbose_name='Rango 7-9 familia'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_14_type',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('familia', 'Familia')], default='unidad', max_length=20, verbose_name='Entrega'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_15',
            field=models.IntegerField(default=0, verbose_name='Conserva de sardina'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_15_0_3',
            field=models.IntegerField(default=0, verbose_name='Rango 0-3 familia'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_15_4_6',
            field=models.IntegerField(default=0, verbose_name='Rango 4-6 familia'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_15_7_9',
            field=models.IntegerField(default=0, verbose_name='Rango 7-9 familia'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_15_type',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('familia', 'Familia')], default='unidad', max_length=20, verbose_name='Entrega'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_16',
            field=models.IntegerField(default=0, verbose_name='Fruta en conserva'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_16_0_3',
            field=models.IntegerField(default=0, verbose_name='Rango 0-3 familia'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_16_4_6',
            field=models.IntegerField(default=0, verbose_name='Rango 4-6 familia'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_16_7_9',
            field=models.IntegerField(default=0, verbose_name='Rango 7-9 familia'),
        ),
        migrations.AddField(
            model_name='alimentosrepatir',
            name='alimento_16_type',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('familia', 'Familia')], default='unidad', max_length=20, verbose_name='Entrega'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_13',
            field=models.IntegerField(default=None, verbose_name='Tarritos infantiles fruta'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_13_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Tarritos infantiles fruta'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_14',
            field=models.IntegerField(default=None, verbose_name='Alubias cocidas'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_14_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Alubias cocidas'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_15',
            field=models.IntegerField(default=None, verbose_name='Conserva de sardina'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_15_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Conserva de sardina'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_16',
            field=models.IntegerField(default=None, verbose_name='Fruta en conserva'),
        ),
        migrations.AddField(
            model_name='almacenalimentos',
            name='alimento_16_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Fruta en conserva'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_10',
            field=models.IntegerField(default=None, verbose_name='Macedonia de verduras en conserva'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_11',
            field=models.IntegerField(default=None, verbose_name='Cacao soluble'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_12',
            field=models.IntegerField(default=None, verbose_name='Tarritos infantiles pollo'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_7',
            field=models.IntegerField(default=None, verbose_name='Tomate frito en conserva (APIS)'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_8',
            field=models.IntegerField(default=None, verbose_name='Tomate frito en conserva (ACICO)'),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='alimento_9',
            field=models.IntegerField(default=None, verbose_name='Galletas'),
        ),
        migrations.AlterField(
            model_name='alimentosrepatir',
            name='alimento_10',
            field=models.IntegerField(default=0, verbose_name='Macedonia de verduras en conserva'),
        ),
        migrations.AlterField(
            model_name='alimentosrepatir',
            name='alimento_11',
            field=models.IntegerField(default=0, verbose_name='Cacao soluble'),
        ),
        migrations.AlterField(
            model_name='alimentosrepatir',
            name='alimento_12',
            field=models.IntegerField(default=0, verbose_name='Tarritos infantiles pollo'),
        ),
        migrations.AlterField(
            model_name='alimentosrepatir',
            name='alimento_7',
            field=models.IntegerField(default=0, verbose_name='Tomate frito en conserva (APIS)'),
        ),
        migrations.AlterField(
            model_name='alimentosrepatir',
            name='alimento_8',
            field=models.IntegerField(default=0, verbose_name='Tomate frito en conserva (ACICO)'),
        ),
        migrations.AlterField(
            model_name='alimentosrepatir',
            name='alimento_9',
            field=models.IntegerField(default=0, verbose_name='Galletas'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_10',
            field=models.IntegerField(default=None, verbose_name='Macedonia de verduras en conserva'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_10_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Macedonia de verduras en conserva'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_11',
            field=models.IntegerField(default=None, verbose_name='Cacao soluble'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_11_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Cacao soluble'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_12',
            field=models.IntegerField(default=None, verbose_name='Tarritos infantiles pollo'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_12_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Tarritos infantiles pollo'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_7',
            field=models.IntegerField(default=None, verbose_name='Tomate frito en conserva (APIS)'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_7_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Tomate frito en conserva (APIS)'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_8',
            field=models.IntegerField(default=None, verbose_name='Tomate frito en conserva (ACICO)'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_8_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Tomate frito en conserva (ACICO)'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_9',
            field=models.IntegerField(default=None, verbose_name='Galletas'),
        ),
        migrations.AlterField(
            model_name='almacenalimentos',
            name='alimento_9_caducidad',
            field=models.DateField(blank=True, default=None, verbose_name='Galletas'),
        ),
    ]
